### ISSUE TITLE
Prompts library import

### ISSUE THREAD

**Issue by jeffscottward** [pfrankov/obsidian-local-gpt#15]
Wondering if you can point to a folder that will pull in a whole lot of custom prompts?

I am using Fabric for example.
https://github.com/danielmiessler/fabric

Instead of having to manually edit them.

**Comment by pfrankov** [comment]
I think that the prompts for CLI and for Obsidian must differ. Instead of a large number of unused prompts and a huge list in the menu, it is much better to use specially prepared prompts, adjusted to work in the editor.
However, nobody prevents you from adding each prompt from Fabric manually or using pre-made Actions that can be added via Quick add https://github.com/pfrankov/obsidian-local-gpt/discussions/2
