### ISSUE TITLE
When I click the refresh button to get models, the dropdown list will disappear

### ISSUE THREAD

**Issue by alabulei1** [pfrankov/obsidian-local-gpt#17]
I'm using another framework to host LLMs, not Ollama. 

When I clicked the refresh button to get models, the dropdown list will disappear. Hence, I can't fetch the model correctly and the plugin doesn't work.

Thanks.

**Comment by vensauro** [comment]
with framework are you using?
Is it Open AI compatible?

**Comment by pfrankov** [comment]
This is due to some connection problem: while the request is running, the button to update the model list is hidden. If a response or error is received, the button is shown again. Unfortunately, having the button and being able to send many requests for the model list will not help you to get the list faster.
I could say that this is expected behavior.
